[[platforms]]
os = "macos"
deleted_patterns = [
  "*.swift*",
  "*iOSSupport*",
  "*Ruby.framework*",
  "*Swift*.framework",
  "*SwiftUI*",
  "System/Cryptexes",
  "System/Library/Perl",
  "usr/lib/swift",
  "usr/libexec",
  "usr/share",
]
