name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macos_build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: ./bazel-cc-sysroot-generator --config examples/macos-config.toml
    - run: ./bazel-cc-sysroot-generator --config examples/sysroot-config.toml

  ubuntu_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: ./bazel-cc-sysroot-generator --config examples/sysroot-config.toml
